services:
  coolify-mcp-server:
    image: 'howieduhzit/coolifymcp:latest'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SERVICE_FQDN_COOLIFY_MCP_SERVER_3000
      - COOLIFY_API_TOKEN=${COOLIFY_API_TOKEN}
      - COOLIFY_BASE_URL=${COOLIFY_BASE_URL:-https://app.coolify.io/api/v1}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - type: bind
        source: '/cool/coolify-mcp-server/logs'
        target: '/app/logs'
      - type: bind
        source: '/cool/coolify-mcp-server/tmp'
        target: '/app/tmp'